### PR TITLE
Fix for scaling issues

### PR DESCRIPTION
**Pull request by Keboo**

### CODE REVIEW

**Comment by Keboo** [comment]
@nicolaihenriksen if you get a chance would you mind testing the latest to see if the DPI issues are resolved by this?

**Comment by nicolaihenriksen** [comment]
> @nicolaihenriksen if you get a chance would you mind testing the latest to see if the DPI issues are resolved by this?

Almost! There was still one test failing, and I added PR #100 which fixes it. I think you probably just forgot to add the precision delta to those assertions since they were present on the ones just above? If they we're intentionally left out, then I guess something else needs fixing...

**Funny observation**
No matter whether I run with 100% or 150% scaling, when running the full suite of tests locally, it seems like nearly all of the spawned WPF windows hang around for quite a long time before the test(s) end up killing them. Is that intentional or some funny side-effect? When I run a(ny) test in isolation, it seems to close the windows immediately after the test finishes...

Here is a screenshot where the test suite has run green for all tests, but is still "running" (i.e. closing windows down slowly). The fat drop-shadow border is a good indication that a lot of windows remain open; Task Manager also clearly shows it.

image

**Comment by nicolaihenriksen** [comment]
@Keboo Oh, and another funny thing. I was actually not able to compile the solution with the latest from master. I had to "unbump" the Microsoft.CodeAnalysus.CSharp" from 4.3.0 back to 4.2.0 in order to compile without errors. I tried deleting nuget cache and even clearing out Visual Studios assembly cache, but it just would not accept it!? Kinda weird since the Github actions workflow runs green in the repo... Any ideas what I could be missing?

**Comment by Keboo** [comment]
It appears to be this particular issue with the 4.3.0 package: https://github.com/dotnet/roslyn/issues/63919

**Comment by Keboo** [comment]
As for the delayed closing of the windows. No that is not intentional. I wonder if the source generator issue is affecting it. I have a PR to address it.

**Comment by nicolaihenriksen** [comment]
> As for the delayed closing of the windows. No that is not intentional. I wonder if the source generator issue is affecting it. I have a PR to address it.

I doubt it, since I had to downgrade in order to run the tests; which means I am effectively NOT experiencing the source generator issue locally at the moment.

**Comment by Keboo** [comment]
Good point, let me look into it further.

**Pull request merged**
