### PR TITLE
Support for timeout message prefix

### PR DESCRIPTION
**Pull request by mgnslndh**
This is a PR for #50. I think this covers the description of #50 along with a few simple tests.

### CODE REVIEW

**Comment by mgnslndh** [comment]
I'm not sure what is the state of the test suite because I had some failing tests after I cloned the repo.

**Comment by mgnslndh** [comment]
Not sure if this repo is part of Hacktoberfest but I wouldn't mind if not too much work and the PR is accepted :)

**Comment by mgnslndh** [comment]
@Keboo anything I need to add or change on this one?

**Review by Keboo — APPROVED** [review]
Sorry for the delay. Lgtm

**Comment by Keboo** [comment]
@mgnslndh and yes it does have the hacktoberfest label (which I believe is all that is required for a repo to opt-in) if there are any issues with it counting for hacktoberfest, let me know.

**Comment by mgnslndh** [comment]
Thanks @Keboo! It is a bit strange because my profile is not updated with this change. Still all the rules are followed; submitted in Oktober, merged PR etc.

**Comment by mgnslndh** [comment]
I've got three PR that seems to have went through the process OK but then there are two other PR (Cake/Website) that are stuck waiting for merge/approval, but they're both merged. When I google this issue I find nothing current and there is no support links :shrug:

I don't think it is a problem with the repos, rather the Hacktoberfest validation code :)

**Comment by Keboo** [comment]
@mgnslndh FWIW I did tweet at hacktoberfest about it. Will see if there is any response.
https://twitter.com/kitokeboo/status/1458823009238597635

**Pull request merged**
